Get some practice with numpy:

https://numpy.org/doc/2.1/user/absolute_beginners.html

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

Create a 1D NumPy array containing the numbers from 1 to 10.

Create a 1D array with 20 evenly spaced numbers between 0 and 1.

In [3]:
a = np.linspace(1, 10, num=10)
print(a)
b = np.linspace(0, 1, num=20)
print(b)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


Create two separate matrices of the same size. Then combine these two matrices row-wise and then column-wise to create the respective new matrix and array.

In [4]:
data1 = np.array([[1, 2], [3, 4], [5, 6]])
data2 = np.array([[7, 8], [9, 10], [11, 12]])
result1 = np.concatenate((data1,data2), axis=0)
result2 = np.concatenate((data1,data2), axis=1)
print(result1)
print(result2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


Create a 3x3 matrix of random numbers.

Create a 4x4 matrix of zeros and then fill the first row with the numbers [1, 2, 3, 4].

In [5]:
matrixrand = np.random.rand(3,3)
print(matrixrand)

matrixzero = np.zeros((4,4))

matrixzero[0] = [1,2,3,4]

print(matrixzero)

[[0.51732398 0.35795644 0.18767911]
 [0.03403624 0.9984191  0.97136032]
 [0.02094461 0.7505423  0.36504474]]
[[1. 2. 3. 4.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Reshape the 1D array of numbers from 1 to 10 into a 2x5 array.

In [6]:
reshape_arr = a.reshape(2,5)
print(reshape_arr)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


Create two 1D arrays of the same length. Stack them vertically and horizontally.

In [7]:
arr1 = np.linspace(1, 10, num=10)
print(arr1)
arr2 = np.linspace(11, 20, num=10)
print(arr2)

rows = np.dstack((arr1,arr2))
print(rows)

cols = np.vstack((arr1,arr2))
print(cols)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
[[[ 1. 11.]
  [ 2. 12.]
  [ 3. 13.]
  [ 4. 14.]
  [ 5. 15.]
  [ 6. 16.]
  [ 7. 17.]
  [ 8. 18.]
  [ 9. 19.]
  [10. 20.]]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]]


Extract the second row and third column of a 4x4 matrix.

Change the value of a specific element in this matrix to 100 using indexing.

In [8]:
print(matrixzero)

second_row = matrixzero[1]
thirdcolumn = matrixzero [:,2]

print(second_row, thirdcolumn)

matrixzero[1, 1] = 3
print(matrixzero)



[[1. 2. 3. 4.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0.] [3. 0. 0. 0.]
[[1. 2. 3. 4.]
 [0. 3. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Replace all even numbers in the array of numbers from 1 to 10 with 0.

Replace all values greater than 5 in the 4x4 random float array with 0.5.

In [15]:

array_1_to_10 = np.arange(1, 11)
array_1_to_10[array_1_to_10 % 2 == 0] = 0
print(array_1_to_10)


random_matrix = np.random.rand(4, 4) * 10
print(random_matrix)

random_matrix[random_matrix > 5] = 0.5
print(random_matrix)


[1 0 3 0 5 0 7 0 9 0]
[[4.46048348 1.62663591 9.16663721 3.08978944]
 [8.23401083 4.93394554 5.98062546 3.62831623]
 [6.76390454 0.97809955 9.15640123 2.94062568]
 [5.1209434  7.5739615  6.9256786  3.75371631]]
[[4.46048348 1.62663591 0.5        3.08978944]
 [0.5        4.93394554 0.5        3.62831623]
 [0.5        0.97809955 0.5        2.94062568]
 [0.5        0.5        0.5        3.75371631]]


Add two arrays element-wise.

Multiply two arrays element-wise.

In [17]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

added_arrays = array1 + array2
print(added_arrays)

multiplied_arrays = array1 * array2
print(multiplied_arrays)


[ 6  8 10 12]
[ 5 12 21 32]


Create a function that sums up the numbers in a randomly generated matrix by rows and by columns.

In [21]:
def sum_rows_and_columns(matrix):
    return np.sum(matrix, axis=1), np.sum(matrix, axis=0)

matrix = np.random.rand(4, 5)
print(matrix)

row_sums, column_sums = sum_rows_and_columns(matrix)
print(row_sums)
print(column_sums)


[[0.83535652 0.17333217 0.33081643 0.242951   0.19270751]
 [0.73808262 0.17046948 0.91805922 0.81899619 0.52289409]
 [0.7542249  0.80645826 0.23347945 0.58031537 0.75177052]
 [0.41376426 0.06351508 0.39936862 0.91713887 0.40940209]]
[1.77516364 3.1685016  3.12624849 2.20318893]
[2.7414283  1.21377499 1.88172373 2.55940143 1.87677422]


Create a function that takes in two matrices and ensures that they can be multiplied, if they can be multiplied, 
multiply them and print the resulting matrix.


In [12]:
# write code here

Find the minimum value of a randomly generated 5x5 matrix with the indices by row and column of where they appear in the matrix.

In [13]:
# write code here