Get some practice with numpy:

https://numpy.org/doc/2.1/user/absolute_beginners.html

In [74]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

Create a 1D NumPy array containing the numbers from 1 to 10.

Create a 1D array with 20 evenly spaced numbers between 0 and 1.

In [13]:
a = np.linspace(1, 10, num=10)
print(a)
b = np.linspace(0, 1, num=20)
print(b)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


Create two separate matrices of the same size. Then combine these two matrices row-wise and then column-wise to create the respective new matrix and array.

In [23]:
data1 = np.array([[1, 2], [3, 4], [5, 6]])
data2 = np.array([[7, 8], [9, 10], [11, 12]])
result1 = np.concatenate((data1,data2), axis=0)
result2 = np.concatenate((data1,data2), axis=1)
print(result1)
print(result2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


Create a 3x3 matrix of random numbers.

Create a 4x4 matrix of zeros and then fill the first row with the numbers [1, 2, 3, 4].

In [33]:
matrixrand = np.random.rand(3,3)
print(matrixrand)

matrixzero = np.zeros((4,4))

matrixzero[0] = [1,2,3,4]

print(matrixzero)

[[0.36510493 0.7336314  0.4596317 ]
 [0.47112856 0.41216198 0.17046148]
 [0.08610415 0.27150839 0.12624445]]
[[1. 2. 3. 4.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Reshape the 1D array of numbers from 1 to 10 into a 2x5 array.

In [32]:
reshape_arr = a.reshape(2,5)
print(reshape_arr)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


Create two 1D arrays of the same length. Stack them vertically and horizontally.

In [52]:
arr1 = np.linspace(1, 10, num=10)
print(arr1)
arr2 = np.linspace(11, 20, num=10)
print(arr2)

rows = np.dstack((arr1,arr2))
print(rows)

cols = np.vstack((arr1,arr2))
print(cols)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
[[[ 1. 11.]
  [ 2. 12.]
  [ 3. 13.]
  [ 4. 14.]
  [ 5. 15.]
  [ 6. 16.]
  [ 7. 17.]
  [ 8. 18.]
  [ 9. 19.]
  [10. 20.]]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]]


Extract the second row and third column of a 4x4 matrix.

Change the value of a specific element in this matrix to 100 using indexing.

In [81]:
print(matrixzero)

second_row = matrixzero[1]
thirdcolumn = matrixzero [:,2]

print(second_row, thirdcolumn)

matrixzero[1, 1] = 3
print(matrixzero)


[[1. 3. 3. 4.]
 [0. 3. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 3. 0. 0.] [3. 0. 0. 0.]
[[1. 3. 3. 4.]
 [0. 3. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Replace all even numbers in the array of numbers from 1 to 10 with 0.

Replace all values greater than 5 in the 4x4 random float array with 0.5.

Add two arrays element-wise.

Multiply two arrays element-wise.

In [ ]:
# write code here

Create a function that sums up the numbers in a randomly generated matrix by rows and by columns.

In [ ]:
# write code here

Create a function that takes in two matrices and ensures that they can be multiplied, if they can be multiplied, 
multiply them and print the resulting matrix.


In [ ]:
# write code here

Find the minimum value of a randomly generated 5x5 matrix with the indices by row and column of where they appear in the matrix.

In [ ]:
# write code here